### ISSUE TITLE
Go build error

### ISSUE THREAD

**Issue by andrewjmackay** [frapposelli/packer-post-processor-vagrant-vmware-ovf#14]
@frapposelli 

Hi, im a newbie when it comes to Go.  Just wondering if you can help me with this Get and Build error.

OSX 10.12.1
go version go1.7.4 darwin/amd64

$ go get -u github.com/frapposelli/packer-post-processor-vagrant-vmware-ovf
$ go build

# github.com/frapposelli/packer-post-processor-vagrant-vmware-ovf
./post-processor.go:179: cannot use &md (type *"github.com/mitchellh/mapstructure".Metadata) as type *"github.com/mitchellh/packer/vendor/github.com/mitchellh/mapstructure".Metadata in field value

**Comment by thekoma** [comment]
+1

**Comment by frapposelli** [comment]
Fixed, please use `make bin` to build it or download the release here https://github.com/frapposelli/packer-post-processor-vagrant-vmware-ovf/releases/tag/v0.2.3
